language: python
python:
    - "3.7"

services:
    - docker
    
before_script:
    - touch .env

# start containers -> sleep 10 secs -> get running containers -> count lines in output ->
# check that 2 containers are running (+1 string of output == 3 strings at all) or travis_terminate
script:
    - docker-compose up -d 
    - sleep 10 && docker container ls | wc -l | xargs test 3 -eq && echo "2 containers are running, all is ok" || echo "some containers are not running, check output" && travis_terminate 1
