version: '3'
services:
  bot:
    build: .
    restart: always
    env_file:
      - .env

  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}