name: digest
channels:
  - defaults
  - conda-forge
dependencies:
  - sqlite=3.29.0
  - psycopg2=2.8.3
  - alembic=1.2.1
  - pip:
    - aiohttp==3.6.1
    - async-timeout==3.0.1
    - attrs==19.1.0
    - chardet==3.0.4
    - idna==2.8
    - idna-ssl==1.1.0
    - nest-asyncio==1.2.0
    - multidict==4.5.2
    - nest-asyncio==1.2.0
    - psycopg2==2.8.3
    - requests==2.22.0
    - six==1.12.0